### ISSUE TITLE
Optimize node transform computation

### ISSUE THREAD

**Issue by Davidster** [Davidster/ikari#48]
it's still taking too much time per frame to update the global transforms of the scene nodes

**Comment by Davidster** [comment]
current plan is to try removing the parent index hash map, and just store a GameNodeId (basically a weak reference) to the parent in the GameNode struct

**Comment by CatCode79** [comment]
Here is my tracy made on the master branch.

Vulkan backend, debug compilation:
![ikari_new_year_vk_debug](https://user-images.githubusercontent.com/12321983/210184720-8fbaea36-b5bd-4f83-a011-47e710565c7d.png)

Vulkan backend, release compilation:
![ikari_new_year_vk_release](https://user-images.githubusercontent.com/12321983/210184723-9104ecac-fc77-400e-8fe5-3da094d3cde2.png)

The difference in average recompute_global_node_transforms time between debug and release is very large, but for now I would say it's not a problem as it improves from debug to release by 60x in speed.

What is striking instead is the time difference of the get_next_texture between debug (just over half a ms) and release (55 ms !!).

(Now i do some tests on the dx12 backend)

**Comment by Davidster** [comment]
does the performance improve if you add this to Cargo.toml?

```
[profile.dev.package."*"]
opt-level = 3
```

I wonder if it's also related to the validation layers that get enabled if you're running in Vulkan in dev mode (I can't quite remember how/when wgpu enables those validations)

**Comment by CatCode79** [comment]
Unfortunately with the dx12 backend I panic (both debug and release).
It was an issue that I recall had happened before but it seems to me that it was resolved somehow.

> [2023-01-01T21:27:01Z INFO  wgpu_core::device] Created buffer Valid((1186, 1, Dx12)) with BufferDescriptor { label: Some("GpuBuffer"), size: 5280, usage: INDEX, mapped_at_creation: true }
[2023-01-01T21:27:01Z INFO  wgpu_core::device] Created buffer Valid((1187, 1, Dx12)) with BufferDescriptor { label: Some("GpuBuffer"), size: 92352, usage: VERTEX, mapped_at_creation: true }
[2023-01-01T21:27:01Z INFO  wgpu_core::device] Created buffer Valid((1188, 1, Dx12)) with BufferDescriptor { label: Some("GpuBuffer"), size: 2640, usage: INDEX, mapped_at_creation: true }
[2023-01-01T21:27:01Z INFO  wgpu_core::device] Created buffer Valid((1189, 1, Dx12)) with BufferDescriptor { label: Some("GpuBuffer"), size: 5280, usage: INDEX, mapped_at_creation: true }
[2023-01-01T21:27:01Z ERROR wgpu_hal::dx12::descriptor] Unable to allocate descriptors: RangeAllocationError { fragmented_free_length: 3 }
[2023-01-01T21:27:01Z ERROR wgpu::backend::direct] Handling wgpu errors as fatal by default
thread 'main' panicked at 'wgpu error: Validation Error
Caused by:
    In Device::create_bind_group
      note: label = `InstancedMeshComponent textures_bind_group`
    not enough memory left
', C:\Users\Gatto\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.14.2\src\backend\direct.rs:2403:5

**Comment by Davidster** [comment]
right yeah that's cuz the scene takes up too much VRAM

**Comment by CatCode79** [comment]
Apparently vulkan uses less vram, since with the same gpu i can start the game.

Tracy-ing with opt-level = 3 gives me similar results as vulkan+release.
![image](https://user-images.githubusercontent.com/12321983/210185485-ad271ff6-8eab-44ba-b0cf-5336e39e9bdc.png)

However, I am noticing that the node update function increases the average time over time.
here after a while, in the same run, it exceeds 1 ms:
![image](https://user-images.githubusercontent.com/12321983/210185523-57430627-9af8-4a3c-895d-04561c5e8d0a.png)

**Comment by CatCode79** [comment]
Instead in release the average time of the recompute_global_node_transforms function decreases over time..
It becomes complicated to test two different modes, I would say to focus on the release for now.

**Comment by Davidster** [comment]
yeah, I'm only worried about optimising release. does the number of objects in the world stay the same during that time?

**Comment by CatCode79** [comment]
Is it the nodes I need to look at? shows me 22.

However I think that bizarre behavior of the mean time that decreases is given by some too high or too low spike that dirty the mean (assuming that the M of MTPC is mean and not median). All in all, the vice versa could also happen, it will be necessary to analyze what happens over the long term.

**Comment by Davidster** [comment]
`game_state.scene.node_count()` should do the trick.

I think tracy has a view where you can see the distribution of the timings for a function which might help identify if the mean is being dirtied by a spike. I'll see if I can get a screenshot of what I'm referring to

**Comment by Davidster** [comment]
Here if you click it you can see the distribution (yellow graph)

![image](https://user-images.githubusercontent.com/2389735/210186274-669c50f3-e1fe-4ae5-af53-e02fdc02385d.png)
